apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kv-asimov-secrets.vault.azure.net/"
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
