---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-applier
  namespace: external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-applier-helm
  namespace: external-secrets
subjects:
- kind: ServiceAccount
  name: flux-applier
  namespace: external-secrets
- kind: ServiceAccount
  name: flux-applier
  namespace: default
roleRef:
  kind: ClusterRole
  name: flux-applier-cluster-admin
  apiGroup: rbac.authorization.k8s.io
