apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-mainsite-auth
  namespace: redis-mainsite
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: redis-mainsite-auth
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: redis-mainsite-password
