apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-mainsite
  namespace: redis-mainsite
  labels:
    app.kubernetes.io/name: redis-mainsite
    app.kubernetes.io/component: redis-cache
spec:
  serviceName: redis-mainsite-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-mainsite
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-mainsite
        app.kubernetes.io/component: redis-cache
    spec:
      nodeSelector:
        kubernetes.azure.com/mode: user
      containers:
        - name: redis
          image: redis:7-alpine
          args:
            - redis-server
            - /etc/redis/redis.conf
            - --requirepass
            - $(REDIS_PASSWORD)
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-mainsite-auth
                  key: redis-password
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/redis
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - $(REDIS_PASSWORD)
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - $(REDIS_PASSWORD)
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: redis-mainsite-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: managed-csi
        resources:
          requests:
            storage: 5Gi
