apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solr-system

resources:
  - ../base

patchesStrategicMerge:
  - solr-operator-values.yaml

commonLabels:
  environment: production
