apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solr-mainsite

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secretproviderclass.yaml
  - solrcloud.yaml
  - security-init-job.yaml

commonLabels:
  app.kubernetes.io/name: solr-mainsite
  app.kubernetes.io/component: solr-search