apiVersion: v1
kind: ServiceAccount
metadata:
  name: solr-mainsite-sa
  namespace: solr-mainsite
  annotations:
    # Azure Workload Identity annotation
    azure.workload.identity/client-id: "4b939dba-5992-46af-94b5-03b2773fa9d4"
  labels:
    azure.workload.identity/use: "true"
