apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - solr-system-namespace.yaml
  - flux-rbac.yaml
  - solr-crds.yaml
  - solr-operator.yaml
  - shared-zookeeper.yaml
  - nginx-ingress.yaml
  - cert-manager.yaml

commonLabels:
  app.kubernetes.io/part-of: solr-operator
