apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - solr-system-namespace.yaml
  - flux-rbac.yaml
  - solr-operator.yaml

commonLabels:
  app.kubernetes.io/part-of: solr-operator
