---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: solr-system
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: solr-system
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.3"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: solr-system
      interval: 12h
  values:
    controller:
      service:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
      # Enable metrics for monitoring
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
      # Configure for AKS
      nodeSelector:
        kubernetes.io/os: linux
      admissionWebhooks:
        patch:
          nodeSelector:
            kubernetes.io/os: linux
      # Set as default ingress class
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
      ingressClass: nginx