apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: polk-correspondence

resources:
  - ../../base/polk-correspondence
  - ingress.yaml
  - root-redirect.yaml

commonLabels:
  environment: production
