apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: polk-correspondence

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: polk-correspondence
  app.kubernetes.io/component: polk-webapp
