apiVersion: v1
kind: Namespace
metadata:
  name: polk-correspondence
  labels:
    name: polk-correspondence
    app.kubernetes.io/name: polk-correspondence
    app.kubernetes.io/component: polk-namespace
