apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solr-volopedia

resources:
  - ../../base/solr-volopedia
  - loadbalancer.yaml

namePrefix: staging-

commonLabels:
  environment: staging