apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: solr-mainsite-staging
  namespace: solr-mainsite-staging
spec:
  # Solr version and replicas
  replicas: 1
  solrImage:
    tag: "9.8.1"

  # Java memory configuration
  solrJavaMem: "-Xms1g -Xmx2g"

  # ZooKeeper reference - using the shared ZooKeeper cluster from infrastructure
  zookeeperRef:
    connectionInfo:
      internalConnectionString: "shared-zookeeper-0.shared-zookeeper-headless.solr-system.svc.cluster.local:2181,shared-zookeeper-1.shared-zookeeper-headless.solr-system.svc.cluster.local:2181,shared-zookeeper-2.shared-zookeeper-headless.solr-system.svc.cluster.local:2181"
      chroot: "/mainsite-staging"

  # Storage configuration
  dataStorage:
    persistent:
      reclaimPolicy: Delete
      pvcTemplate:
        spec:
          storageClassName: default
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

  # Update strategy
  updateStrategy:
    method: "Managed"
    managed:
      maxPodsUnavailable: 1

  # Solr configuration
  solrOpts: "-Dsolr.autoSoftCommit.maxTime=10000"

  # Security configuration - operator will bootstrap security.json automatically
  # Creates admin, solr, and k8s-oper users with random passwords
  # Passwords stored in: solr-mainsite-staging-solrcloud-security-bootstrap secret
  solrSecurity:
    authenticationType: Basic
    probesRequireAuth: false  # Allow health probes without authentication

  # Pod configuration
  customSolrKubeOptions:
    podOptions:
      # Resource requests/limits - must account for JVM heap (2g) + overhead
      resources:
        requests:
          memory: "2560Mi"
          cpu: "500m"
        limits:
          memory: "3Gi"
          cpu: "2000m"

      # Ensure pods run on user nodes, not system nodes
      nodeSelector:
        kubernetes.azure.com/mode: user

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  solr-cloud: solr-mainsite-staging
              topologyKey: kubernetes.io/hostname

      # Environment variables
      envVars:
      - name: SOLR_LOG_LEVEL
        value: "INFO"
      - name: GC_TUNE
        value: "-XX:+UseG1GC -XX:+UseStringDeduplication"

  # Service configuration for external access
  solrAddressability:
    external:
      method: Ingress
      domainName: "libsolr.lib.utk.edu"
      hideCommon: false
    commonServicePort: 8983
    kubeDomain: "cluster.local"
