apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solr-volopedia

resources:
  - namespace.yaml
  - zookeeper.yaml
  - solrcloud.yaml

commonLabels:
  app.kubernetes.io/name: solr-volopedia
  app.kubernetes.io/component: solr-search