apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - monitoring-namespace.yaml
  - flux-rbac.yaml
  - kube-prometheus-stack.yaml
  - grafana-admin-externalsecret.yaml
  - grafana-oauth-externalsecret.yaml
  - alertmanager-config-externalsecret.yaml
  - node-capacity-dashboard.yaml
  - node-capacity-alerts.yaml
  - alerts-overview-dashboard.yaml
  - vireo-traefik-podmonitor.yaml
  - vireo-traefik-dashboard.yaml
  - blackbox-exporter.yaml
  - blackbox-probes.yaml
  - blackbox-alerts.yaml
  - blackbox-dashboard.yaml

commonLabels:
  app.kubernetes.io/part-of: kube-prometheus-stack
